# -*- coding: utf-8 -*-
"""fileUpload.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ne9Y2_0ai588-MkLC2X3vkJOwXVABt-L
"""

############################################
#売上情報をアップロード
############################################

import pandas as pd
import datetime
import pandas.tseries.offsets as offsets
from dateutil.relativedelta import relativedelta
from google.colab import files
import imageio

!rm -rf *.xlsx

inputs = []
images = []

uploaded = files.upload()

df=pd.read_excel(list(uploaded)[0],sheet_name="all")